on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: sed -i 's/1\.0\.0/${{github.event.release.tag_name}}/g' Cargo.toml
      - name: Prereqs
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends xz-utils liblz4-tool musl-tools
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup update
          rustup target add aarch64-unknown-linux-gnu
      - run: |
          cargo build --target=aarch64-unknown-linux-gnu --release
          zip -r aarch-linux.zip target/aarch64-unknown-linux-gnu/release/whynotblog -j
          gh release upload ${{github.event.release.tag_name}} aarch-linux.zip
